linkyard/concourse-helm-resource

- wait-for-helm-deployment/src/parse-helm.ts
- wait-for-helm-deployment/test/parse-helm-spec.ts
Partially implements #6 
Just uses the last part of the kubernetes type for matching (ie `Service` instead of `v1/Service`.
> Quick fix for making wait-for more robust

- README.md
- assets/out
Added support for Helms `--recreate-pods` flag when running `helm upgrade`, https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#helpful-options-for-installupgraderollback
> Add support for --recreate-pods

- README.md
- assets/out
- test/payload.json.template
allows versions prepended with a hyphen and series of identifiers to be installed without having to also specify the version
when versioning our charts, we sometimes end up with `1.0.2-rc0` and don't want to have to also specify the chart version in the params so it'd be great if we could also set the `--devel` flag when running `helm install/upgrade`.
> expose --devel flag in params for installing a chart

- README.md
- assets/out
Fixes #24 
A quick attempt to hide secret values from the log when putting a chart resource.
It just duplicates the `helm_cmd` variable into `helm_echo`, and adds `***HIDDEN***` in place of the real value if the `hide` parameter is set to `true` for each key in the `override_values` list.
> Hide secret values

- assets/out
While debugging I noticed the payload files weren't being generate in the `/tmp` folder as expected rather in the root of the container E.G. `/helm-helm-resource-request.bAkkA3`.
The manpage for `mktemp` states to use a directory:
```
-p DIR, --tmpdir[=DIR]
interpret TEMPLATE relative to DIR; if DIR is not specified, use $TMPDIR if set, else /tmp.  With this option,  TEMPLATE  must  not  be  an
absolute name; unlike with -t, TEMPLATE may contain slashes, but mktemp creates only the final component
```
so by using `$TMPDIR` which is empty in the container image, the payload files were being forced to the root directory.
> Cleanup mktemp

- assets/out
Fixes #19 
Allows for deployments of charts from a directory while a more comprehensive approach is implemented.
> Triage for regression of deployment of chart from directory

- assets/out
Sorry, my last PR was incomplete.
I am passing certificates with the override_file option. The newlines in the certificates got mangled, so they became unusable. This fixes it.
> Fix eval mangling newlines

- Dockerfile
- assets/out
> Fix first install on failed first deployment

- assets/common.sh
When using the concourse-helm-resource with a service account with the minimum privileges as per https://github.com/kubernetes/helm/blob/master/docs/rbac.md#example-deploy-helm-in-a-namespace-talking-to-tiller-in-another-namespace and http://technosophos.com/2017/11/20/securing-helm.html the cluster-info command fails. It seems that cluster-info isn't really necessary.
Since the version bump of kubectl from `1.8.4` to `1.9.6` an error is returned due to insufficient permissions: 
```
Initializing kubectl...
Cluster "default" set.
User "admin" set.
Context "default" created.
Switched to context "default".
Kubernetes master is running at https://myk8smaster
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Error from server (Forbidden): services is forbidden: …
```
> Remove the cluster-info call

- assets/out
This allows another resource (e.g. git-maintained version file) to provide the version to the helm resource.
> Allow --version to be populated from file

- assets/out
the helm upgrade command already has the build-in option to install if the release doesn't exist. 
Therefore we can simplify the whole out part by making 1 generic upgrade command and adding the  `--install` option so helm can manage the install if it doesn't exist.
https://docs.helm.sh/helm/#helm-upgrade
> use helm upgrade as default command for installing/upgrading

- assets/out
`helm status` doesn't show the version, so I think this hasn't worked
since switching from `helm history`. The previous churn around this was
to avoid an issue with gPRC max message sizes, which has been fixed in
Helm 2.8.2, and which is now used by this project.
> `out` correctly gets new release version

- README.md
- assets/common.sh
Allows passing a value to set the `HELM_HOST` environment variable.
This makes Helm skip creating a port forwarder tunnel to Tiller.
See https://github.com/linkyard/concourse-helm-resource/issues/45
> Add helm_host source configuration setting

- README.md
- assets/common.sh
Helm 2.9 adds support for basic auth. This commit adds support for the
new flag when setting repos.
Also removes the need for `cut`, using `jq` instead.
Closes #52
> Add support for username and password

- Dockerfile
Blocked by linkyard/docker-helm#9
> Update Helm to 2.9.0

- README.md
- assets/out
Adds the ability to configure a namespace in the same way we configure
releases, per job.
Closes #55
> Add namespace to job params

- assets/out
Currently anything one passes as `params.release` or `params.namespace` are interpreted as literal release or namespace names, even if they're invalid names (eg. with directory separators in them) and a file with that name exists.
Apparently it was https://github.com/linkyard/concourse-helm-resource/pull/50 broke the ability to pass a filename for `params.release`.
> fix: detection if 'params.release' and 'params.namespace' are files

- Dockerfile
- assets/out
helm diff v2.9.0+2 adds the `--allow-unreleased` flag which shows the full helm release as a diff if the release is brand new. Without this flag, helm diff errors. Currently, the workaround is to not provide the `helm_diff: true` parameter during the first `put` and to only add it later.
Also change the Dockerfile so take KUBERNETES_VERSION as a build-time ARG, and bump it to the latest release (1.10.4).
> `helm diff` supports new releases

- assets/out
- Changes `current_revision` to `current_deployed` to store the Helm history as a variable before awking for metadata 
- Adds chart version to `metadata` (but not `version` but I'm good with either)
Can be tested with [this Docker image](https://hub.docker.com/r/arbourd/concourse-helm-resource/builds/bcwqxn9e6ss5bi6n7cjopwr/).
Closes #67
> Adds chart version to metadata

- README.md
- assets/out
Running `debug` is way too mistaking. To fully use the power of `helm diff`, I've added a flag to exit before the helm install/upgrade to get the diff without going the actually deployment. It forces you to have 2 JOBS one with the new flag and one without but at least you can gate what you deploy.
> Add option to exit after *helm diff*

- README.md
- assets/out
This PR adds support for a `type: string` parameter in `override_values`. This parameter makes the resource use the `--set-string` option of Helm (instead of the `--set` option) for the given value override. It can be used to ensure that Helm always treats the value as a string, useful if the value varies and may look like a number, eg. if it's a Git commit hash. See also https://github.com/kubernetes/helm/issues/1707
> Allow setting values as string

- Dockerfile
Use the latest `linkyard/docker-helm` image: https://github.com/linkyard/docker-helm/releases/tag/2.10.0
> Updates helm to v2.10.0

- assets/common.sh
Instead of calling `helm repo update` for each repo, do it once at the
end of the setup / init process.
> Update repositories once

- assets/check
We are currently seeing the following on any of our jobs with this resource
```
Resource setup successful.
Error: could not find tiller
```
Pulling in the `.source.tiller_namespace` looks to solve the issue and brings the script up-to-date with the others.
> set tiller-namespace in check script

- README.md
- assets/out
Add reuse-values option for helm upgrade. For example, when upgrading, I want only change image tag, it can reuse the last release's values.
> Add reuse-values option

- assets/check
We have a release with more then 256 deployments and run into this error:
```
Error: grpc: trying to send message larger than max (25314892 vs. 20971520)
```
This fixes check for the resource
> Fix listing of big historys in check

- Dockerfile
Now that `linkyard/docker-helm:2.12.2` is available (from linkyard/docker-helm#19), it'd be good to bump up the resource 😁
I also bumped the kubectl version to the latest patch.
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
> Updating to helm 2.12.2

- README.md
- assets/check
- assets/common.sh
- assets/out
Allow the concourse-helm-resource to be used in put-only mode with a
kubeconfig file.
This builds off of pr46, but extends it so that there is no need to
configure the resource with the cluster_url (or anything else specified
in the kubeconfig).
Additionally, add a number of additional related controls:
- Get the k8s namespace from the kubeconfig file
- Ability to configure the tiller namespace
- Ability to enable tracing for debugging the resource
- Expose the helm init --wait option
- Ability to specify the kubeconfig path on put.
Together, these features allow us to use the helm resource in conjunction
with the pool resource and the kubernetes resource to:
- Dynamically pick a k8s namespace from a pool, granting exclusive access
- Run a helm-based standalone integration test against a …
> feat: Enable pool kubeconfig pattern

- assets/common.sh
With my setup, I get the following error:
```
Initializing kubectl...
/opt/resource/common.sh: line 35: /root/.kube/key.pem: No such file or directory
```
This should fix it.
> Make sure /root/.kube always exists

- assets/common.sh
This PR fix the use of authentication through HTTPS `server_url`, using `server_ca` and `token`.
The build break with the following log:
```
Initializing kubectl...
/opt/resource/common.sh: line 29: /root/.kube/ca.pem: No such file or directory
```
Successful build… Or, at least no error at the resource level.
> Make sure /root/.config really exists

- assets/out
This makes sure chart dependencies for local charts are downloaded before performing the helm upgrade.
Fixes: https://github.com/linkyard/concourse-helm-resource/issues/51
>  Install dependencies for local charts

- README.md
- assets/out
If you want helm to reset the values of your deployment you need to use --reset-values.   This is good to combat manual changes to deployments with a redeploy.  This enables that feature in this resource.
let me know if i missed something
> adding the option for reset-values

- README.md
- assets/out
Fixes #130
Add a `verbatim: true` parameter to `override_values` to escape backslashes passed to `helm --set`.
> Escape override_values

- Dockerfile
- assets/out
Allow expanding env variables such as Concourse metadata resource (see https://concourse-ci.org/implementing-resource-types.html#resource-metadata)
> Expand env variables such as metadata resource

- README.md
- assets/out
Behavior of the `--atomic` flag:
- Failed installs will purge the release
- Failed upgrades will rollback to the previous release
Exists in Helm 2.14.x and upward.
https://v2-14-0.helm.sh/docs/helm/#helm-install
https://v2-14-0.helm.sh/docs/helm/#helm-upgrade
> Add support for --atomic flag

- Dockerfile
Doing this because Helm 2.16.4 has a pretty important fix for indeterministic Helm upgrade errors.
See. https://github.com/helm/helm/issues/6031#issuecomment-570068395
This is live on Helm 2.16.4 https://github.com/helm/helm/releases/tag/v2.16.4
> Updating Helm to 2.16.4

- assets/out
Closes https://github.com/linkyard/concourse-helm-resource/issues/129.
In the instance where `helm history` or `helm ls` is called there is really no reason to retrieve the last 20 revisions. Especially because the only purpose of executing these commands is to parse and obtain the `release` name. 
Furthermore, in situations where a release may contain a large amount of data we can hit the gRPC size limit as outlined in the issue.
> Limit helm history and list commands to one revision

- assets/out
This option was added (https://github.com/helm/helm/pull/4871) in helm `2.14` and is a useful complement to `--atomic`, making sure that all side-effects of a failed upgrade are removed.
> Add cleanup_on_fail option
